# generated by datamodel-codegen:
#   filename:  resume.schema.json
#   timestamp: 2025-03-24T16:30:02+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class PersonalInformation(BaseModel):
    title: Optional[str] = None
    summary: Optional[str] = None


class ProfessionalExperienceItem(BaseModel):
    position: str
    company: str
    location: Optional[str] = None
    start_date: str = Field(..., alias='startDate')
    end_date: Optional[str] = Field(None, alias='endDate')
    responsibilities: Optional[List[str]] = None


class EducationItem(BaseModel):
    degree: str
    field: Optional[str] = None
    institution: str
    location: Optional[str] = None
    graduation_date: Optional[str] = Field(None, alias='graduationDate')
    start_date: Optional[str] = Field(None, alias='startDate')
    end_date: Optional[str] = Field(None, alias='endDate')
    gpa: Optional[str] = None


class Certification(BaseModel):
    name: str
    date: Optional[str] = None


class MilitaryServiceItem(BaseModel):
    branch: Optional[str] = None
    rank: Optional[str] = None
    start_date: Optional[str] = Field(None, alias='startDate')
    end_date: Optional[str] = Field(None, alias='endDate')
    responsibilities: Optional[List[str]] = None


class ResumeSchema(BaseModel):
    personal_information: PersonalInformation = Field(..., alias='personalInformation')
    highlights: Optional[List[str]] = None
    accomplishments: Optional[List[str]] = None
    professional_experience: List[ProfessionalExperienceItem] = Field(
        ..., alias='professionalExperience'
    )
    education: Optional[List[EducationItem]] = None
    skills: Optional[List[str]] = None
    certifications: Optional[List[Certification]] = None
    military_service: Optional[List[MilitaryServiceItem]] = Field(
        None, alias='militaryService'
    )
    interests: Optional[List[str]] = None
