# This is a config for E2B sandbox template.
# You can use template ID (dtpa9vsgs7ggc8brb4i0) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("dtpa9vsgs7ggc8brb4i0") # Sync sandbox
# sandbox = await AsyncSandbox.create("dtpa9vsgs7ggc8brb4i0") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('dtpa9vsgs7ggc8brb4i0')

team_id = "f04d247a-4561-49cd-9a10-8b0fdd3ad38a"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "dtpa9vsgs7ggc8brb4i0"
